// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectDirectory() {
  return window['go']['document']['Document']['SelectDirectory']();
}

export function Startup(arg1) {
  return window['go']['document']['Document']['Startup'](arg1);
}
