// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {document} from '../models';
import {context} from '../models';

export function GetFolderTree(arg1:string):Promise<Array<document.FileSystemItem>>;

export function SelectDirectory():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
