// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDocument(arg1) {
  return window['go']['document']['Document']['CreateDocument'](arg1);
}

export function CreateInvoiceTemplate(arg1) {
  return window['go']['document']['Document']['CreateInvoiceTemplate'](arg1);
}

export function CreatePreset(arg1) {
  return window['go']['document']['Document']['CreatePreset'](arg1);
}

export function CreatePresetItem(arg1) {
  return window['go']['document']['Document']['CreatePresetItem'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['document']['Document']['DeleteDocument'](arg1);
}

export function DeleteInvoiceTemplate(arg1) {
  return window['go']['document']['Document']['DeleteInvoiceTemplate'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['document']['Document']['DeletePreset'](arg1);
}

export function DeletePresetItem(arg1) {
  return window['go']['document']['Document']['DeletePresetItem'](arg1);
}

export function ExtractVariables(arg1) {
  return window['go']['document']['Document']['ExtractVariables'](arg1);
}

export function ExtractVariablesFromFile(arg1) {
  return window['go']['document']['Document']['ExtractVariablesFromFile'](arg1);
}

export function ExtractVariablesFromFiles(arg1) {
  return window['go']['document']['Document']['ExtractVariablesFromFiles'](arg1);
}

export function GetAllDocuments() {
  return window['go']['document']['Document']['GetAllDocuments']();
}

export function GetAllFacilities() {
  return window['go']['document']['Document']['GetAllFacilities']();
}

export function GetAllInvoiceTemplates() {
  return window['go']['document']['Document']['GetAllInvoiceTemplates']();
}

export function GetAllPresets() {
  return window['go']['document']['Document']['GetAllPresets']();
}

export function GetDocumentByID(arg1) {
  return window['go']['document']['Document']['GetDocumentByID'](arg1);
}

export function GetFolderTree(arg1) {
  return window['go']['document']['Document']['GetFolderTree'](arg1);
}

export function GetInvoiceTargets() {
  return window['go']['document']['Document']['GetInvoiceTargets']();
}

export function GetPresetByID(arg1) {
  return window['go']['document']['Document']['GetPresetByID'](arg1);
}

export function GetReplacementStatistics(arg1, arg2) {
  return window['go']['document']['Document']['GetReplacementStatistics'](arg1, arg2);
}

export function GetUnreplacedVariables(arg1, arg2) {
  return window['go']['document']['Document']['GetUnreplacedVariables'](arg1, arg2);
}

export function ProcessSelectedFiles(arg1, arg2, arg3) {
  return window['go']['document']['Document']['ProcessSelectedFiles'](arg1, arg2, arg3);
}

export function ReplaceVariables(arg1, arg2) {
  return window['go']['document']['Document']['ReplaceVariables'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['document']['Document']['SelectDirectory']();
}

export function SelectExcelFile() {
  return window['go']['document']['Document']['SelectExcelFile']();
}

export function Startup(arg1) {
  return window['go']['document']['Document']['Startup'](arg1);
}

export function UpdateDocument(arg1) {
  return window['go']['document']['Document']['UpdateDocument'](arg1);
}

export function UpdateInvoiceTemplate(arg1) {
  return window['go']['document']['Document']['UpdateInvoiceTemplate'](arg1);
}

export function UpdatePreset(arg1) {
  return window['go']['document']['Document']['UpdatePreset'](arg1);
}

export function UpdatePresetItem(arg1) {
  return window['go']['document']['Document']['UpdatePresetItem'](arg1);
}

export function ValidateInvoiceExcel(arg1) {
  return window['go']['document']['Document']['ValidateInvoiceExcel'](arg1);
}

export function ValidateVariables(arg1, arg2) {
  return window['go']['document']['Document']['ValidateVariables'](arg1, arg2);
}
