// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDocumentsInFolder(arg1) {
  return window['go']['services']['DocumentService']['GetDocumentsInFolder'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['services']['DocumentService']['OpenFile'](arg1);
}

export function ProcessExcelDocument(arg1, arg2, arg3) {
  return window['go']['services']['DocumentService']['ProcessExcelDocument'](arg1, arg2, arg3);
}

export function ProcessFiles(arg1, arg2, arg3) {
  return window['go']['services']['DocumentService']['ProcessFiles'](arg1, arg2, arg3);
}

export function ProcessWordDocument(arg1, arg2, arg3) {
  return window['go']['services']['DocumentService']['ProcessWordDocument'](arg1, arg2, arg3);
}

export function ReadFolderAndDocument(arg1) {
  return window['go']['services']['DocumentService']['ReadFolderAndDocument'](arg1);
}

export function ShowInExplorer(arg1) {
  return window['go']['services']['DocumentService']['ShowInExplorer'](arg1);
}
