// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetDocumentsInFolder(arg1:string):Promise<Array<services.FileNode>>;

export function OpenFile(arg1:string):Promise<void>;

export function ProcessExcelDocument(arg1:string,arg2:string,arg3:{[key: string]: string}):Promise<void>;

export function ProcessFiles(arg1:Array<string>,arg2:string,arg3:{[key: string]: string}):Promise<number>;

export function ProcessWordDocument(arg1:string,arg2:string,arg3:{[key: string]: string}):Promise<void>;

export function ReadFolderAndDocument(arg1:string):Promise<services.FileNode>;

export function ShowInExplorer(arg1:string):Promise<void>;
