// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateFacility(arg1:models.FacilityModel):Promise<models.FacilityModel>;

export function CreateManager(arg1:models.ManagerModel):Promise<models.ManagerModel>;

export function CreatePartner(arg1:models.PartnerModel):Promise<models.PartnerModel>;

export function CreatePartnerNote(arg1:models.PartnerNoteModel):Promise<models.PartnerNoteModel>;

export function DeleteFacility(arg1:number):Promise<void>;

export function DeleteManager(arg1:number):Promise<void>;

export function DeletePartner(arg1:number):Promise<void>;

export function DeletePartnerNote(arg1:number):Promise<void>;

export function GetAllManagers():Promise<Array<models.ManagerModel>>;

export function GetAllPartners():Promise<Array<models.PartnerModel>>;

export function GetAllSettings():Promise<Array<models.SettingModel>>;

export function GetFacilitiesByPartnerID(arg1:number):Promise<Array<models.FacilityModel>>;

export function GetFacilityByID(arg1:number):Promise<models.FacilityModel>;

export function GetFacilityDocumentsByFacilityID(arg1:number):Promise<Array<models.FacilityDocumentModel>>;

export function GetManagerByID(arg1:number):Promise<models.ManagerModel>;

export function GetManagersByFacilityID(arg1:number):Promise<Array<models.ManagerModel>>;

export function GetManagersByPartnerID(arg1:number):Promise<Array<models.ManagerModel>>;

export function GetPartnerByID(arg1:number):Promise<models.PartnerModel>;

export function GetPartnerNotesByPartnerID(arg1:number):Promise<Array<models.PartnerNoteModel>>;

export function GetSettingByKey(arg1:string):Promise<models.SettingModel>;

export function Greet(arg1:string):Promise<string>;

export function SaveFacilityDocuments(arg1:number,arg2:Array<string>):Promise<void>;

export function UpdateFacility(arg1:models.FacilityModel):Promise<void>;

export function UpdateManager(arg1:models.ManagerModel):Promise<void>;

export function UpdatePartner(arg1:models.PartnerModel):Promise<void>;

export function UpdatePartnerNote(arg1:models.PartnerNoteModel):Promise<void>;

export function UpdateSetting(arg1:models.SettingModel):Promise<void>;
