// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFacility(arg1) {
  return window['go']['main']['App']['CreateFacility'](arg1);
}

export function CreateManager(arg1) {
  return window['go']['main']['App']['CreateManager'](arg1);
}

export function CreatePartner(arg1) {
  return window['go']['main']['App']['CreatePartner'](arg1);
}

export function CreatePartnerNote(arg1) {
  return window['go']['main']['App']['CreatePartnerNote'](arg1);
}

export function DeleteFacility(arg1) {
  return window['go']['main']['App']['DeleteFacility'](arg1);
}

export function DeleteManager(arg1) {
  return window['go']['main']['App']['DeleteManager'](arg1);
}

export function DeletePartner(arg1) {
  return window['go']['main']['App']['DeletePartner'](arg1);
}

export function DeletePartnerNote(arg1) {
  return window['go']['main']['App']['DeletePartnerNote'](arg1);
}

export function GetAllManagers() {
  return window['go']['main']['App']['GetAllManagers']();
}

export function GetAllPartners() {
  return window['go']['main']['App']['GetAllPartners']();
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetFacilitiesByPartnerID(arg1) {
  return window['go']['main']['App']['GetFacilitiesByPartnerID'](arg1);
}

export function GetFacilityByID(arg1) {
  return window['go']['main']['App']['GetFacilityByID'](arg1);
}

export function GetFacilityDocumentsByFacilityID(arg1) {
  return window['go']['main']['App']['GetFacilityDocumentsByFacilityID'](arg1);
}

export function GetManagerByID(arg1) {
  return window['go']['main']['App']['GetManagerByID'](arg1);
}

export function GetManagersByFacilityID(arg1) {
  return window['go']['main']['App']['GetManagersByFacilityID'](arg1);
}

export function GetManagersByPartnerID(arg1) {
  return window['go']['main']['App']['GetManagersByPartnerID'](arg1);
}

export function GetPartnerByID(arg1) {
  return window['go']['main']['App']['GetPartnerByID'](arg1);
}

export function GetPartnerNotesByPartnerID(arg1) {
  return window['go']['main']['App']['GetPartnerNotesByPartnerID'](arg1);
}

export function GetSettingByKey(arg1) {
  return window['go']['main']['App']['GetSettingByKey'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveFacilityDocuments(arg1, arg2) {
  return window['go']['main']['App']['SaveFacilityDocuments'](arg1, arg2);
}

export function UpdateFacility(arg1) {
  return window['go']['main']['App']['UpdateFacility'](arg1);
}

export function UpdateManager(arg1) {
  return window['go']['main']['App']['UpdateManager'](arg1);
}

export function UpdatePartner(arg1) {
  return window['go']['main']['App']['UpdatePartner'](arg1);
}

export function UpdatePartnerNote(arg1) {
  return window['go']['main']['App']['UpdatePartnerNote'](arg1);
}

export function UpdateSetting(arg1) {
  return window['go']['main']['App']['UpdateSetting'](arg1);
}
